# Generated by Django 3.2.12 on 2022-04-14 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('epicevents', '0002_auto_20220414_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_name',
            field=models.CharField(default='contract', max_length=250),
        ),
        migrations.AddField(
            model_name='contract',
            name='signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_contact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='sales_contact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='epicevents.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_contact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
