# Generated by Django 3.2.12 on 2022-05-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epicevents', '0008_alter_client_client_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_name',
            field=models.CharField(max_length=250),
        ),
    ]
