# Generated by Django 3.2.12 on 2022-05-12 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epicevents', '0009_alter_contract_contract_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contract_reference',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='epicevents.contract'),
        ),
    ]
